### ISSUE TITLE
Cmake not being able to find netcdf-cxx installed with autotools

### ISSUE THREAD

**Issue by draenog** [nextsimhub/nextsimdg#81]
Current cmake configuration is able to discover location of netcdf-cxx only when it was installed using cmake. However the library also supports installation using autotools and it is the modes used for example by spack and easubuild. In this case netCDFConfig.cmake is not present. Instead it is possible to use pkg-config to locate the library in this case

**Comment by TomMelt** [comment]
@draenog I think this issue has been resolved by PR #84 . I managed to install with spack version of netcdf just fine. Am I missing something?

**Comment by draenog** [comment]
In general both netcdf-c and netcdf-cxx can be installed with cmake or autotools. So in general there  are four possible cases. I think the mixed cases are still not handled.

**Comment by TomMelt** [comment]
Ah so, for example, if netcdf-c is installed with autotools but netcdf-cxx is installed with cmake then the build will fail?
